language: go

go:
  - "1.10"

before_install:
  - go get github.com/mitchellh/gox
  - dep ensure

script:
  - dep ensure
  - go test
  - gox -os="linux darwin windows" -arch="amd64" -output="logshare.{{.OS}}.{{.Arch}}" -ldflags "-X main.Rev=`git rev-parse --short HEAD`" -verbose
  - ls
